services:
    senky.userstatistics.listener:
        class: senky\userstatistics\event\listener
        arguments:
            - @dbal.conn
            - @template
            - @user
        tags:
            - { name: event.listener }
